/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lnc' at '5/25/17 6:15 PM' with Gradle 2.14
 *
 * @author lnc, @date 5/25/17 6:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
